"""empty message

Revision ID: 61c2e786e8de
Revises: c31158e4e66d
Create Date: 2022-07-20 15:47:01.918282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61c2e786e8de'
down_revision = 'c31158e4e66d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('statia', 'created_post_date',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.add_column('user', sa.Column('secret_word', sa.String(length=4), nullable=False))
    op.add_column('user', sa.Column('account_created_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'account_created_time')
    op.drop_column('user', 'secret_word')
    op.alter_column('statia', 'created_post_date',
               existing_type=sa.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###
