"""added secret into base

Revision ID: a3904a6f8b58
Revises: af06bc58563b
Create Date: 2022-07-17 17:39:41.833410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3904a6f8b58'
down_revision = 'af06bc58563b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('secret', sa.String(length=4), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'secret')
    # ### end Alembic commands ###
