"""added date

Revision ID: c31158e4e66d
Revises: a3904a6f8b58
Create Date: 2022-07-20 12:46:09.653676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c31158e4e66d'
down_revision = 'a3904a6f8b58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statia', sa.Column('created_post_date', sa.DateTime(), nullable=False))
    op.add_column('user', sa.Column('created_date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'created_date')
    op.drop_column('statia', 'created_post_date')
    # ### end Alembic commands ###
